# **Imports**

In [25]:
import pandas as pd

import matplotlib.pyplot as plt

import numpy as np

In [26]:
wego = pd.read_csv("./Headway Data, 8-1-2023 to 9-30-2023.csv")

# **Exploration**

In [27]:
wego

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF,DWELL_IN_MINS,SCHEDULED_LAYOVER_MINUTES
0,120230801,1,99457890,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,6.500000,NaN
1,120230801,1,99457891,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,0.000000,NaN
2,120230801,1,99457892,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,0.000000,NaN
3,120230801,1,99457893,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,NaN,0,0.000000,NaN
4,120230801,1,99457894,2023-08-01,22,2200,1040,345105,0,FROM DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,12.866666,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350324,120230930,2,100406610,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,35.266666,5.266666,0,1,0,0,0.0,0,0.000000,NaN
350325,120230930,2,100406611,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,NaN,NaN,0,1,0,0,NaN,0,0.000000,NaN
350326,120230930,2,100406612,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,31.866666,1.866666,0,0,1,0,0.0,0,0.000000,NaN
350327,120230930,2,100406613,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,47.500000,17.500000,0,1,0,0,0.0,0,0.000000,NaN
350328,120230930,2,100406614,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,NaN,NaN,0,1,0,0,NaN,0,3.216666,NaN

In [28]:
wego.columns

Index(['CALENDAR_ID', 'SERVICE_ABBR', 'ADHERENCE_ID', 'DATE', 'ROUTE_ABBR',
       'BLOCK_ABBR', 'OPERATOR', 'TRIP_ID', 'OVERLOAD_ID',
       'ROUTE_DIRECTION_NAME', 'TIME_POINT_ABBR', 'ROUTE_STOP_SEQUENCE',
       'TRIP_EDGE', 'LATITUDE', 'LONGITUDE', 'SCHEDULED_TIME',
       'ACTUAL_ARRIVAL_TIME', 'ACTUAL_DEPARTURE_TIME', 'ADHERENCE',
       'SCHEDULED_HDWY', 'ACTUAL_HDWY', 'HDWY_DEV', 'ADJUSTED_EARLY_COUNT',
       'ADJUSTED_LATE_COUNT', 'ADJUSTED_ONTIME_COUNT', 'STOP_CANCELLED',
       'PREV_SCHED_STOP_CANCELLED', 'IS_RELIEF', 'DWELL_IN_MINS',
       'SCHEDULED_LAYOVER_MINUTES'],
      dtype='object')

In [29]:
wego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350329 entries, 0 to 350328
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CALENDAR_ID                350329 non-null  int64
 1   SERVICE_ABBR               350329 non-null  int64
 2   ADHERENCE_ID               350329 non-null  int64
 3   DATE                       350329 non-null  object
 4   ROUTE_ABBR                 350329 non-null  int64
 5   BLOCK_ABBR                 350329 non-null  int64
 6   OPERATOR                   350329 non-null  int64
 7   TRIP_ID                    350329 non-null  int64
 8   OVERLOAD_ID                350329 non-null  int64
 9   ROUTE_DIRECTION_NAME       350329 non-null  object
 10  TIME_POINT_ABBR            350329 non-null  object
 11  ROUTE_STOP_SEQUENCE        350318 non-null  float64
 12  TRIP_EDGE                  350329 non-null  int64
 13  LATITUDE                   350329 non-null  float64
 14  LONGITUDE                  350329 non-null  float64
 15  SCHEDULED_TIME             350329 non-null  object
 16  ACTUAL_ARRIVAL_TIME        338870 non-null  object
 17  ACTUAL_DEPARTURE_TIME      338861 non-null  object
 18  ADHERENCE                  338861 non-null  float64
 19  SCHEDULED_HDWY             274738 non-null  float64
 20  ACTUAL_HDWY                266062 non-null  float64
 21  HDWY_DEV                   265893 non-null  float64
 22  ADJUSTED_EARLY_COUNT       350329 non-null  int64
 23  ADJUSTED_LATE_COUNT        350329 non-null  int64
 24  ADJUSTED_ONTIME_COUNT      350329 non-null  int64
 25  STOP_CANCELLED             350329 non-null  int64
 26  PREV_SCHED_STOP_CANCELLED  280000 non-null  float64
 27  IS_RELIEF                  350329 non-null  int64
 28  DWELL_IN_MINS              338858 non-null  float64
 29  SCHEDULED_LAYOVER_MINUTES  53102 non-null   float64
dtypes: float64(10), int64(14), object(6)
memory usage: 80.2+ MB

In [30]:
type(wego)

pandas.core.frame.DataFrame

# **Q1**

What is the overall on-time performance, and what do the overall distribution of adherence look like?

In [35]:
# tracking if adherence column meets guidelines and storing boolean into a new column
wego['adh_track'] = (wego[['ADHERENCE']] > -6) & (wego[['ADHERENCE']] < 1)

In [37]:
# looking at the new column made to compare
wego[['adh_track', 'ADHERENCE']]

        adh_track  ADHERENCE
0            True  -2.133333
1            True  -2.450000
2            True  -0.933333
3           False   6.283333
4            True  -1.583333
...           ...        ...
350324      False  -8.433333
350325      False -11.300000
350326       True  -4.316666
350327      False -22.083333
350328      False -23.666666

[350329 rows x 2 columns]

In [46]:
# filtered out the False booleans
on_time = wego[wego['adh_track'] == True] 

# filters out the TRIP_EDGE type 2 since these are not considered early or late b/c it is the last stop of the day
not_last_stop = on_time[on_time['TRIP_EDGE'] != 2]

not_last_stop[['TRIP_EDGE']]

        TRIP_EDGE
0               1
1               0
2               0
4               1
5               0
...           ...
350314          1
350315          0
350317          1
350320          1
350326          1

[217107 rows x 1 columns]

In [42]:
#find the %age of how many are on time
overall_on_time = len(on_time) / len(wego) * 100

overall_on_time

70.28222042708425

# **Q4**

How much of a factor does the driver have on on-time performance? The driver is indicated by the OPERATOR variable.