# **Imports**

In [47]:
pip install dataframe_image

Collecting dataframe_image
  Downloading dataframe_image-0.2.7-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pandas>=0.24 in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (2.2.3)
Requirement already satisfied: nbconvert>=5 in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (7.16.6)
Requirement already satisfied: aiohttp>=3.10.2 in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (3.11.10)
Requirement already satisfied: requests in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (2.32.3)
Requirement already satisfied: pillow in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (11.1.0)
Requirement already satisfied: packaging in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (24.2)
Requirement already satisfied: mistune in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (3.1.2)
Requirement already satisfied: lxml in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (5.3.0)
Requirement already satisfied: beautifulsoup4 in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (4.12.3)
Collecting cssutils (from dataframe_image)
  Downloading cssutils-2.11.1-py3-none-any.whl.metadata (8.7 kB)
Collecting playwright (from dataframe_image)
  Downloading playwright-1.55.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: cssselect in c:\users\craft\anaconda3\lib\site-packages (from dataframe_image) (1.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\craft\anaconda3\lib\site-packages (from aiohttp>=3.10.2->dataframe_image) (1.18.0)
Requirement already satisfied: idna>=2.0 in c:\users\craft\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp>=3.10.2->dataframe_image) (3.7)
Requirement already satisfied: bleach!=5.0.0 in c:\users\craft\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=5->dataframe_image) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.7.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (2.19.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\craft\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.14.3)
Requirement already satisfied: webencodings in c:\users\craft\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->dataframe_image) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\craft\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=5->dataframe_image) (1.4.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\craft\anaconda3\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe_image) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\craft\anaconda3\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe_image) (308)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\craft\anaconda3\lib\site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe_image) (8.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\craft\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (2.9.0.post0)
Requirement already satisfied: pyzmq>=23.0 in c:\users\craft\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (26.2.0)
Requirement already satisfied: tornado>=6.2 in c:\users\craft\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (6.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\craft\anaconda3\lib\site-packages (from nbformat>=5.7->nbconvert>=5->dataframe_image) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\craft\anaconda3\lib\site-packages (from nbformat>=5.7->nbconvert>=5->dataframe_image) (4.23.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\craft\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\craft\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\craft\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image) (0.22.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\craft\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\craft\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\craft\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\craft\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\craft\anaconda3\lib\site-packages (from beautifulsoup4->dataframe_image) (2.5)
Requirement already satisfied: more-itertools in c:\users\craft\anaconda3\lib\site-packages (from cssutils->dataframe_image) (10.3.0)
Collecting pyee<14,>=13 (from playwright->dataframe_image)
  Downloading pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in c:\users\craft\anaconda3\lib\site-packages (from playwright->dataframe_image) (3.1.1)
Requirement already satisfied: typing-extensions in c:\users\craft\anaconda3\lib\site-packages (from pyee<14,>=13->playwright->dataframe_image) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\craft\anaconda3\lib\site-packages (from requests->dataframe_image) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\craft\anaconda3\lib\site-packages (from requests->dataframe_image) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\craft\anaconda3\lib\site-packages (from requests->dataframe_image) (2025.8.3)
Downloading dataframe_image-0.2.7-py3-none-any.whl (6.7 MB)
   ---------------------------------------- 0.0/6.7 MB ? eta -:--:--
   ------------------------------- -------- 5.2/6.7 MB 33.2 MB/s eta 0:00:01
   ---------------------------------------- 6.7/6.7 MB 30.2 MB/s eta 0:00:00
Downloading cssutils-2.11.1-py3-none-any.whl (385 kB)
Downloading playwright-1.55.0-py3-none-win_amd64.whl (35.5 MB)
   ---------------------------------------- 0.0/35.5 MB ? eta -:--:--
   --------------- ------------------------ 13.9/35.5 MB 66.0 MB/s eta 0:00:01
   ------------------------------------ --- 32.8/35.5 MB 79.8 MB/s eta 0:00:01
   ---------------------------------------- 35.5/35.5 MB 63.2 MB/s eta 0:00:00
Downloading pyee-13.0.0-py3-none-any.whl (15 kB)
Installing collected packages: pyee, cssutils, playwright, dataframe_image

   ---------- ----------------------------- 1/4 [cssutils]
   ---------- ----------------------------- 1/4 [cssutils]
   ---------- ----------------------------- 1/4 [cssutils]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   -------------------- ------------------- 2/4 [playwright]
   ------------------------------ --------- 3/4 [dataframe_image]
   ---------------------------------------- 4/4 [dataframe_image]

Successfully installed cssutils-2.11.1 dataframe_image-0.2.7 playwright-1.55.0 pyee-13.0.0
Note: you may need to restart the kernel to use updated packages.

In [60]:
import pandas as pd

import matplotlib.pyplot as plt

import numpy as np

import dataframe_image as dfi

from matplotlib.colors import LinearSegmentedColormap

In [2]:
wego = pd.read_csv("./Headway Data, 8-1-2023 to 9-30-2023.csv")

# **Exploration**

In [3]:
wego

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF,DWELL_IN_MINS,SCHEDULED_LAYOVER_MINUTES
0,120230801,1,99457890,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,6.500000,NaN
1,120230801,1,99457891,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,0.000000,NaN
2,120230801,1,99457892,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,0.000000,NaN
3,120230801,1,99457893,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,NaN,0,0,1,0,NaN,0,0.000000,NaN
4,120230801,1,99457894,2023-08-01,22,2200,1040,345105,0,FROM DOWNTOWN,...,NaN,NaN,0,0,1,0,0.0,0,12.866666,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350324,120230930,2,100406610,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,35.266666,5.266666,0,1,0,0,0.0,0,0.000000,NaN
350325,120230930,2,100406611,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,NaN,NaN,0,1,0,0,NaN,0,0.000000,NaN
350326,120230930,2,100406612,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,31.866666,1.866666,0,0,1,0,0.0,0,0.000000,NaN
350327,120230930,2,100406613,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,47.500000,17.500000,0,1,0,0,0.0,0,0.000000,NaN
350328,120230930,2,100406614,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,NaN,NaN,0,1,0,0,NaN,0,3.216666,NaN

In [4]:
wego.columns

Index(['CALENDAR_ID', 'SERVICE_ABBR', 'ADHERENCE_ID', 'DATE', 'ROUTE_ABBR',
       'BLOCK_ABBR', 'OPERATOR', 'TRIP_ID', 'OVERLOAD_ID',
       'ROUTE_DIRECTION_NAME', 'TIME_POINT_ABBR', 'ROUTE_STOP_SEQUENCE',
       'TRIP_EDGE', 'LATITUDE', 'LONGITUDE', 'SCHEDULED_TIME',
       'ACTUAL_ARRIVAL_TIME', 'ACTUAL_DEPARTURE_TIME', 'ADHERENCE',
       'SCHEDULED_HDWY', 'ACTUAL_HDWY', 'HDWY_DEV', 'ADJUSTED_EARLY_COUNT',
       'ADJUSTED_LATE_COUNT', 'ADJUSTED_ONTIME_COUNT', 'STOP_CANCELLED',
       'PREV_SCHED_STOP_CANCELLED', 'IS_RELIEF', 'DWELL_IN_MINS',
       'SCHEDULED_LAYOVER_MINUTES'],
      dtype='object')

In [5]:
wego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350329 entries, 0 to 350328
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CALENDAR_ID                350329 non-null  int64
 1   SERVICE_ABBR               350329 non-null  int64
 2   ADHERENCE_ID               350329 non-null  int64
 3   DATE                       350329 non-null  object
 4   ROUTE_ABBR                 350329 non-null  int64
 5   BLOCK_ABBR                 350329 non-null  int64
 6   OPERATOR                   350329 non-null  int64
 7   TRIP_ID                    350329 non-null  int64
 8   OVERLOAD_ID                350329 non-null  int64
 9   ROUTE_DIRECTION_NAME       350329 non-null  object
 10  TIME_POINT_ABBR            350329 non-null  object
 11  ROUTE_STOP_SEQUENCE        350318 non-null  float64
 12  TRIP_EDGE                  350329 non-null  int64
 13  LATITUDE                   350329 non-null  float64
 14  LONGITUDE                  350329 non-null  float64
 15  SCHEDULED_TIME             350329 non-null  object
 16  ACTUAL_ARRIVAL_TIME        338870 non-null  object
 17  ACTUAL_DEPARTURE_TIME      338861 non-null  object
 18  ADHERENCE                  338861 non-null  float64
 19  SCHEDULED_HDWY             274738 non-null  float64
 20  ACTUAL_HDWY                266062 non-null  float64
 21  HDWY_DEV                   265893 non-null  float64
 22  ADJUSTED_EARLY_COUNT       350329 non-null  int64
 23  ADJUSTED_LATE_COUNT        350329 non-null  int64
 24  ADJUSTED_ONTIME_COUNT      350329 non-null  int64
 25  STOP_CANCELLED             350329 non-null  int64
 26  PREV_SCHED_STOP_CANCELLED  280000 non-null  float64
 27  IS_RELIEF                  350329 non-null  int64
 28  DWELL_IN_MINS              338858 non-null  float64
 29  SCHEDULED_LAYOVER_MINUTES  53102 non-null   float64
dtypes: float64(10), int64(14), object(6)
memory usage: 80.2+ MB

In [6]:
type(wego)

pandas.core.frame.DataFrame

# **Q1**

What is the overall on-time performance, and what do the overall distribution of adherence look like?

In [7]:
working_table = wego.copy()

In [8]:
avg_ontime = working_table['ADJUSTED_ONTIME_COUNT'].mean()
avg_ontime

np.float64(0.7708411236295025)

In [9]:
working_table['ON_TIME'] = np.where((working_table['ADHERENCE'].notnull()) & (working_table['ADHERENCE'].between(-6, 6)), 1, 0)
working_table

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF,DWELL_IN_MINS,SCHEDULED_LAYOVER_MINUTES,ON_TIME
0,120230801,1,99457890,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,0,0,1,0,0.0,0,6.500000,NaN,1
1,120230801,1,99457891,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,0,0,1,0,0.0,0,0.000000,NaN,1
2,120230801,1,99457892,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,0,0,1,0,0.0,0,0.000000,NaN,1
3,120230801,1,99457893,2023-08-01,22,2200,1040,345104,0,TO DOWNTOWN,...,NaN,0,0,1,0,NaN,0,0.000000,NaN,0
4,120230801,1,99457894,2023-08-01,22,2200,1040,345105,0,FROM DOWNTOWN,...,NaN,0,0,1,0,0.0,0,12.866666,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350324,120230930,2,100406610,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,5.266666,0,1,0,0,0.0,0,0.000000,NaN,0
350325,120230930,2,100406611,2023-09-30,7,702,2312,353448,0,TO DOWNTOWN,...,NaN,0,1,0,0,NaN,0,0.000000,NaN,0
350326,120230930,2,100406612,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,1.866666,0,0,1,0,0.0,0,0.000000,NaN,1
350327,120230930,2,100406613,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,17.500000,0,1,0,0,0.0,0,0.000000,NaN,0
350328,120230930,2,100406614,2023-09-30,7,702,2312,353449,0,FROM DOWNTOWN,...,NaN,0,1,0,0,NaN,0,3.216666,NaN,0

In [76]:
working_table.to_csv('Workingtable.csv', index=False)

In [10]:
total_count = working_table['ADHERENCE'].notnull().sum()
ontime_count = working_table['ON_TIME'].sum()
ontime_perc = (ontime_count / total_count) * 100

In [11]:
print(f"Overall On-Time Performance: {ontime_perc:.2f}%")

Overall On-Time Performance: 81.75%

# **Q4**

How much of a factor does the driver have on on-time performance? The driver is indicated by the OPERATOR variable.

In [12]:
wego.columns

Index(['CALENDAR_ID', 'SERVICE_ABBR', 'ADHERENCE_ID', 'DATE', 'ROUTE_ABBR',
       'BLOCK_ABBR', 'OPERATOR', 'TRIP_ID', 'OVERLOAD_ID',
       'ROUTE_DIRECTION_NAME', 'TIME_POINT_ABBR', 'ROUTE_STOP_SEQUENCE',
       'TRIP_EDGE', 'LATITUDE', 'LONGITUDE', 'SCHEDULED_TIME',
       'ACTUAL_ARRIVAL_TIME', 'ACTUAL_DEPARTURE_TIME', 'ADHERENCE',
       'SCHEDULED_HDWY', 'ACTUAL_HDWY', 'HDWY_DEV', 'ADJUSTED_EARLY_COUNT',
       'ADJUSTED_LATE_COUNT', 'ADJUSTED_ONTIME_COUNT', 'STOP_CANCELLED',
       'PREV_SCHED_STOP_CANCELLED', 'IS_RELIEF', 'DWELL_IN_MINS',
       'SCHEDULED_LAYOVER_MINUTES'],
      dtype='object')

In [13]:
drivers = wego.groupby('OPERATOR', as_index=False)[
    ['ADJUSTED_EARLY_COUNT', 'ADJUSTED_LATE_COUNT', 'ADJUSTED_ONTIME_COUNT']
].sum()

drivers

,OPERATOR,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT
0,0,0,0,1
1,56,0,0,3
2,235,1,5,6
3,244,0,5,20
4,301,1,17,19
...,...,...,...,...
336,3149,4,8,76
337,3156,0,71,219
338,3165,0,20,12
339,3166,0,3,32
340,3173,0,2,20

In [14]:
# New column to calculate each operators adherence
drivers['TOTAL_COUNTS'] = (drivers['ADJUSTED_EARLY_COUNT'] + drivers['ADJUSTED_LATE_COUNT'] + drivers['ADJUSTED_ONTIME_COUNT'] )

In [15]:
drivers['ONTIME_PERC'] = round((drivers['ADJUSTED_ONTIME_COUNT'] / drivers['TOTAL_COUNTS'] * 100), 2)

In [16]:
drivers = drivers.sort_values('ONTIME_PERC', ascending=False)

In [17]:
drivers = drivers.reset_index(drop=True)

In [18]:
drivers

,OPERATOR,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,TOTAL_COUNTS,ONTIME_PERC
0,0,0,0,1,1,100.00
1,56,0,0,3,3,100.00
2,2294,0,0,45,45,100.00
3,1762,16,23,2294,2333,98.33
4,1706,1,0,43,44,97.73
...,...,...,...,...,...,...
336,2094,5,24,9,38,23.68
337,1377,0,48,12,60,20.00
338,2982,0,26,2,28,7.14
339,473,0,1,0,1,0.00
340,656,0,1,0,1,0.00

In [19]:
drivers.to_csv('WeGo_drivers_dataset.csv', index=False)

In [25]:
correlation = drivers.corr()

In [26]:
correlation.to_csv('Driver_Correlation.csv', index=False)

In [54]:
correlation = correlation.iloc[3:6, 3:6]

In [72]:
bus_lightyear_colors = ["#512DA8", "#1976D2", "#FFFFFF", "#8BC34A"]

bus_lightyear_cmap = LinearSegmentedColormap.from_list("bus_lightyear", bus_lightyear_colors)

In [73]:
correlation_styled = correlation.style.background_gradient(cmap=bus_lightyear_cmap) #adding a gradient based on values in cell

correlation_styled

In [74]:
corr_long = (
    correlation
    .reset_index()                      # turn the row index into a column
    .melt(id_vars='index',              # melt all other columns
          var_name='Variable2',         # name for the column headers
          value_name='Correlation')     # name for the correlation values
    .rename(columns={'index': 'Variable1'})
)

In [75]:
corr_long

               Variable1              Variable2  Correlation
0  ADJUSTED_ONTIME_COUNT  ADJUSTED_ONTIME_COUNT     1.000000
1           TOTAL_COUNTS  ADJUSTED_ONTIME_COUNT     0.976711
2            ONTIME_PERC  ADJUSTED_ONTIME_COUNT     0.369155
3  ADJUSTED_ONTIME_COUNT           TOTAL_COUNTS     0.976711
4           TOTAL_COUNTS           TOTAL_COUNTS     1.000000
5            ONTIME_PERC           TOTAL_COUNTS     0.247266
6  ADJUSTED_ONTIME_COUNT            ONTIME_PERC     0.369155
7           TOTAL_COUNTS            ONTIME_PERC     0.247266
8            ONTIME_PERC            ONTIME_PERC     1.000000

In [30]:
corr_long['Correlation'] = corr_long['Correlation'].round(3)

In [32]:
corr_long.to_csv('correlation_long.csv', index=False)